### PR TITLE
add categories

### PR DESCRIPTION
**Pull request by sysyrin**
1. add sample categories in saber-config.yml
2. set category in the sample post
3. display category in the homepage

issue no: #3

### CODE REVIEW

**Comment by iCyris** [comment]
Hello @SherOnDale ,

Thanks for the pull request.

The idea displaying category in the homepage is great, I'll add it to my todo list and make some tweaks by the way (Like adding a beautiful icon before the category). But I think adding sample categories in the config file is a complicated work. 🤔

**Comment by sysyrin** [comment]
It depends on personal preference ig, some might like predefined categories and others may want them to be more dynamic. so ig you want it to be more dynamic?

**Comment by iCyris** [comment]
Yep :D

**Comment by sysyrin** [comment]
also these tags are supposed to be a replacement for categories?

**Comment by iCyris** [comment]
No, tags and categories are different to some degree, `category` will be added later, but for now I'm still designing where to position it (on posts pages). Also I plan to  make a `tag cloud` page and `category`  page to display all the categories/tags,  it may take some time 😅.

By the way, tags function on `saber-theme-ume@1.1.0` has some problems. It seems `saber-plugin-query-posts` went wrong somewhere, I'll fix it soon.

**Comment by sysyrin** [comment]
Cool, do let me know if there is something I can help with :p

**Comment by iCyris** [comment]
The problem of tags was fixed in `saber-theme-ume@1.2.0`. also if you use categories, it will be displayed on `/categories/your-category` as the [doc](https://github.com/egoist/saber/tree/master/packages/saber-plugin-query-posts#categories) said.

Well...If u have any ideas about the `tag cloud` page, new pull request is welcomed XD! I'm stuck with it...

**Comment by sysyrin** [comment]
could you tell me more about what a tag cloud page is?

**Comment by iCyris** [comment]
like [this](https://veritas501.space/tags/).

**Comment by iCyris** [comment]
I have opened an [issue](https://github.com/iCyris/Ume/issues/6) to talk about the `tag cloud page`, we can talk there and I'd close this pr. Any good ideas about the theme, issues and pr are welcomed :D.

**Pull request closed without merging**
